parameters:
  seq_column: sequence
  protacc_column: accessions
  intensity_column: 
  start_column: start
  end_column: end
  out_dir: DN02_Brain_class_2
  mod_pattern: (,)
  delimiter: ;
  prot_accession: 
  plateau_csv: 
  min_overlap: 11
  max_step_size: 5
  min_epi_length: 11

