name: testrelease

on:
  release:
    types: [published]  

jobs:
  setup_and_build:
    name: Build and publish package on testpypi
    runs-on: ubuntu-latest
    environment:
      name: testrelease
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: python dependencies
        run: >-
          python -m pip install --upgrade pip build
          pip install .

      - name: Build
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish to testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip_existing: true
