name: test

on: 
  pull_request:
    branches:
      - [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install pytest

      - name: test epicore
        run: pytest tests/epicore_test.py

    