name: testrelease

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  setup_and_build:
    name: Build and publish package on testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/epicore

    steps:
      - uses: actions/checkout@v4

      - name: Set up python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pypa/build
        run: >-
          python -m pip install --upgrade pip

      - name: Install package and its dependencies
        run: pip install . 

      - name: Publish to testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip_existing: true
