name: Update version in epicore_utils/__init__.py

on:
  release:
    types: [published]

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Update __version__ in __init__.py
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        echo "Updating version to $VERSION in __init__.py"
        sed -i "s/__version__=.*/__version__='$VERSION'/" epicore_utils/__init__.py
        head epicore_utils/__init__.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epicore_utils/__init__.py
        git commit -m 'update version in __init__.py with new release version'
        git push 
